"use client";
import {useEffect,useRef,useState,lazy,Suspense} from 'react';
import {ArrowUpRight,ArrowDown,Play,Pause,Menu,X,Plus,ChevronLeft,ChevronRight,MapPin} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import gsap from 'gsap';import {ScrollTrigger} from 'gsap/ScrollTrigger';
const PlanExplorer=lazy(()=>import('./PlanExplorer'));
const media=[{file:'saphira-estar',name:'Estar integrado'},{file:'saphira-interior',name:'Jantar e convivência'},{file:'saphira-detalhe',name:'Texturas e conforto'},{file:'saphira-cozinha',name:'Cozinha e materiais'}];
const wa=(project='Saphira Residence')=>'https://wa.me/554988194537?text='+encodeURIComponent('Olá! Gostaria de receber mais informações sobre o '+project+'.');
const mapQuery=encodeURIComponent('Rua Ari Waltrick da Silva, 277, Universitário, Lages, SC');
function Logo({className=''}:{className?:string}){return <img className={'logo '+className} src="/images/lumon-logo.png" alt="Lumon Construtora e Incorporadora" width="230" height="116"/>}
function Photo({file,alt,className=''}:{file:string,alt:string,className?:string}){return <img className={className} src={'/images/'+file+'.jpg'} alt={alt} decoding="async" onError={e=>{const el=e.currentTarget;if(!el.dataset.retried){el.dataset.retried='1';el.src='/images/'+file+'.webp'}}}/>}
export default function Home(){
 const root=useRef<HTMLDivElement>(null),intro=useRef<HTMLDivElement>(null),heroVideo=useRef<HTMLVideoElement>(null),journey=useRef<HTMLElement>(null);
 const [entered,setEntered]=useState(false),[menu,setMenu]=useState(false),[film,setFilm]=useState(false),[gallery,setGallery]=useState<number|null>(null),[planOpen,setPlanOpen]=useState(false),[paused,setPaused]=useState(false),[chapter,setChapter]=useState(0),[unit,setUnit]=useState('apartamento'),[scrolled,setScrolled]=useState(false);
 const enter=()=>{if(!intro.current)return;gsap.to(intro.current,{clipPath:'inset(0 0 100% 0)',duration:1.15,ease:'power4.inOut',onComplete:()=>setEntered(true)});};
 useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const seen=sessionStorage.getItem('lumon-visited');if(seen||reduced){setEntered(true)}else{const t=setTimeout(()=>{enter();sessionStorage.setItem('lumon-visited','1')},2300);return()=>clearTimeout(t)}},[]);
 useEffect(()=>{if(!entered)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced){heroVideo.current?.pause();setPaused(true)};
 const ctx=gsap.context(()=>{if(!reduced){gsap.fromTo('.hero-title span',{yPercent:110},{yPercent:0,duration:1.3,stagger:.13,ease:'power3.out'});gsap.to('.hero-foot',{y:60,opacity:0,scrollTrigger:{trigger:'.hero',start:'50% top',end:'bottom top',scrub:true}});gsap.fromTo('.opening-image',{clipPath:'inset(12% 15% 12% 15%)'},{clipPath:'inset(0% 0% 0% 0%)',scrollTrigger:{trigger:'.opening-image',start:'top 85%',end:'center center',scrub:1}});
 const tl=gsap.timeline({scrollTrigger:{trigger:'.visual-journey',start:'top top',end:'bottom bottom',scrub:.8,onUpdate:s=>setChapter(Math.min(2,Math.floor(s.progress*3)))}});tl.fromTo('.journey-image-1',{clipPath:'inset(100% 0% 0% 0%)'},{clipPath:'inset(0% 0% 0% 0%)',duration:1},.6).fromTo('.journey-image-2',{clipPath:'inset(100% 0% 0% 0%)'},{clipPath:'inset(0% 0% 0% 0%)',duration:1},1.8).to({}, {duration:.6});
 gsap.utils.toArray<HTMLElement>('.image-reveal').forEach(el=>gsap.fromTo(el,{clipPath:'inset(8% 0 8% 0)'},{clipPath:'inset(0% 0 0% 0)',duration:1.1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 85%',once:true}}));}
 },root);const onScroll=()=>setScrolled(scrollY>100);window.addEventListener('scroll',onScroll,{passive:true});onScroll();return()=>{ctx.revert();window.removeEventListener('scroll',onScroll)}},[entered]);
 useEffect(()=>{if(gallery===null)return;const f=(e:KeyboardEvent)=>{if(e.key==='ArrowRight')setGallery(v=>v===null?null:(v+1)%media.length);if(e.key==='ArrowLeft')setGallery(v=>v===null?null:(v+media.length-1)%media.length)};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[gallery]);
 const chapterTo=(i:number)=>{if(!journey.current)return;window.scrollTo({top:journey.current.offsetTop+(journey.current.offsetHeight-innerHeight)*[.04,.5,.92][i],behavior:'smooth'})};
 const pause=()=>{if(paused){heroVideo.current?.play().then(()=>setPaused(false)).catch(()=>{})}else{heroVideo.current?.pause();setPaused(true)}};
 return <div ref={root}>
 {!entered&&<div className="brand-intro" ref={intro}><Logo/><p>CONSTRUIR É DAR FORMA AO FUTURO.</p><div className="intro-line"/><button onClick={enter}>Entrar <ArrowUpRight size={16}/></button></div>}
 <a href="#saphira" className="skip">Ir para o empreendimento</a>
 <header className={'site-header '+(scrolled?'solid':'')}><a href="#inicio" aria-label="Lumon, início"><Logo/></a><nav aria-label="Menu principal"><a href="#saphira">Saphira</a><a href="#planta">Planta interativa</a><a href="#localizacao">Localização</a></nav><a className="header-cta" href={wa()} target="_blank" rel="noreferrer">Fale com a Lumon <ArrowUpRight size={16}/></a><button className="menu-open" onClick={()=>setMenu(true)} aria-label="Abrir menu"><Menu/></button></header>
 <main>
 <section className="hero" id="inicio"><video ref={heroVideo} src="/images/saphira-filme.mp4" poster="/images/saphira-fachada.jpg" autoPlay muted loop playsInline preload="auto" aria-label="Fachada do Saphira Residence em movimento"/><div className="hero-veil"/><div className="hero-topline"><span>UNIVERSITÁRIO, LAGES — SC</span><span>UM EMPREENDIMENTO LUMON</span></div><div className="hero-title"><span>Saphira</span><span className="residence-word">RESIDENCE</span></div><div className="hero-foot"><a href="#saphira" className="discover">Arquitetura para viver.<ArrowDown size={19}/></a><button className="film-button" onClick={()=>setFilm(true)}><span><Play size={15} fill="currentColor"/></span>O filme</button></div><button className="pause-video" onClick={pause} aria-label={paused?'Reproduzir vídeo':'Pausar vídeo'}>{paused?<Play size={15}/>:<Pause size={15}/>}</button></section>
 <section className="opening" id="saphira"><div className="opening-heading"><span className="overline">SAPHIRA RESIDENCE</span><h1>O espaço certo.<br/><span>Para a sua vida.</span></h1><div className="opening-description"><p>Studios e apartamentos de 2 dormitórios no bairro Universitário. Arquitetura contemporânea, ambientes integrados e o cuidado da Lumon em cada escolha.</p><a href="#planta">Encontre seu espaço <ArrowUpRight size={18}/></a></div></div><div className="opening-image"><Photo file="saphira-fachada" alt="Perspectiva frontal das duas torres do Saphira Residence"/><div className="opening-image-label"><span>DESENHADO PARA O SEU PRÓXIMO CAPÍTULO.</span><div><b>30—70</b><span>m² · plantas disponíveis</span></div></div></div></section>
 <section className="visual-journey" ref={journey} id="ambientes"><div className="journey-stage"><div className="journey-photo journey-image-0"><Photo file="saphira-estar" alt="Sala de estar do Saphira com painel de madeira e sofá claro"/></div><div className="journey-photo journey-image-1"><Photo file="saphira-interior" alt="Ambiente de jantar integrado do Saphira"/></div><div className="journey-photo journey-image-2"><Photo file="saphira-detalhe" alt="Detalhe do sofá e das texturas claras do Saphira"/></div><div className="journey-vignette"/><div className="journey-caption" key={chapter}><span className="overline">DENTRO DO SAPHIRA</span><h2>{['Viver.','Receber.','Desacelerar.'][chapter]}</h2><p>{['O estar se abre para a casa. A madeira traz o aconchego.','Espaços conectados para compartilhar o dia a dia.','Luz, texturas e a tranquilidade de estar em casa.'][chapter]}</p></div><div className="journey-selector" aria-label="Explorar ambientes">{['Estar','Convivência','Detalhes'].map((s,i)=><button key={s} className={chapter===i?'active':''} onClick={()=>chapterTo(i)}>{s}</button>)}</div><span className="visual-note">Perspectivas ilustrativas do empreendimento</span></div></section>
 <section className="gallery-strip" aria-label="Galeria de interiores"><div className="gallery-intro"><span className="overline">MAIS DE PERTO</span><h2>Os detalhes<br/>fazem a casa.</h2><p>Madeira, luz e tons naturais.<br/>Selecione para ampliar.</p></div><div className="gallery-track">{media.map((m,i)=><button key={m.file} onClick={()=>setGallery(i)} aria-label={'Ampliar '+m.name}><Photo file={m.file} alt={m.name}/><span>{m.name}<Plus size={18}/></span></button>)}</div></section>
 <section className="floor-section" id="planta"><div className="floor-heading"><span className="overline">UM ESPAÇO QUE VOCÊ PODE EXPLORAR</span><h2>Imagine a sua rotina.<br/><span>Por outro ângulo.</span></h2></div><Tabs value={unit} onValueChange={setUnit} className="unit-tabs"><TabsList aria-label="Tipologias" className="typology-list"><TabsTrigger value="apartamento">2 dormitórios</TabsTrigger><TabsTrigger value="studio">Studios</TabsTrigger></TabsList><TabsContent value="apartamento"><Suspense fallback={<div className="model-placeholder">Preparando a planta interativa…</div>}><PlanExplorer/></Suspense><div className="plan-bottom"><button onClick={()=>setPlanOpen(true)}>Ver a planta original <Plus size={16}/></button><a href={wa('Saphira Residence — apartamento de 2 dormitórios')} target="_blank" rel="noreferrer">Consultar esta tipologia <ArrowUpRight size={18}/></a></div></TabsContent><TabsContent value="studio"><div className="studio-view"><Photo file="saphira-interior" alt="Perspectiva ilustrativa dos interiores do Saphira"/><div><span className="overline">PRATICIDADE PARA O DIA A DIA</span><h3>Seu primeiro espaço.<br/>Novas possibilidades.</h3><p>Conheça as opções de studios do Saphira e consulte a planta, a metragem e a disponibilidade com nossa equipe.</p><a className="line-link" href={wa('Saphira Residence — studios')} target="_blank" rel="noreferrer">Receber as plantas dos studios <ArrowUpRight size={18}/></a><small>Imagem ilustrativa dos interiores do empreendimento.</small></div></div></TabsContent></Tabs></section>
 <section className="location-section" id="localizacao"><div className="address-block"><span className="overline">SEU ENDEREÇO EM LAGES</span><h2>Universitário.</h2><address>Rua Ari Waltrick da Silva, 277<br/>Universitário · Lages · Santa Catarina</address><a className="line-link" href={'https://www.google.com/maps/search/?api=1&query='+mapQuery} target="_blank" rel="noreferrer">Abrir endereço no Google Maps <ArrowUpRight size={18}/></a></div><div className="map-frame"><iframe title="Localização do Saphira Residence — Rua Ari Waltrick da Silva, 277, Lages" src={'https://maps.google.com/maps?q='+mapQuery+'&z=16&output=embed'} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><a href={'https://www.google.com/maps/search/?api=1&query='+mapQuery} target="_blank" rel="noreferrer"><MapPin size={16}/> Ver localização e traçar rota <ArrowUpRight size={16}/></a></div></section>
 <section className="company-section" id="lumon"><div className="company-image image-reveal"><Photo file="saphira-perspectiva" alt="Perspectiva arquitetônica do Saphira, um projeto Lumon"/></div><div className="company-copy"><Logo/><h2>De Lages.<br/>Para o futuro.</h2><p>Há mais de 10 anos, a Lumon desenvolve, incorpora e executa projetos residenciais que unem design e qualidade de vida.</p><a className="line-link" href="https://www.instagram.com/lumon_construtora/" target="_blank" rel="noreferrer">Acompanhe nossos projetos <ArrowUpRight size={18}/></a></div></section>
 <section className="monticello" id="monticello"><div className="monticello-top"><span className="overline">TAMBÉM ASSINADO PELA LUMON</span><h2>Monticello</h2><a href={wa('Residencial Monticello')} target="_blank" rel="noreferrer">Conheça o empreendimento <ArrowUpRight size={18}/></a></div><div className="monticello-content"><div className="monticello-photo image-reveal"><Photo file="monticello" alt="Perspectiva arquitetônica do Residencial Monticello"/></div><div className="monticello-details"><p>Ambientes ensolarados.<br/>Uma nova vista para viver.</p><ul><li>Salão de festas</li><li>Infraestrutura para ar-condicionado</li><li>Água quente e central de gás</li><li>Medidores individuais</li><li>Fechaduras eletrônicas</li></ul><small>Consulte a fase atual da obra e a possibilidade de personalizar os acabamentos.</small></div></div></section>
 <section className="contact" id="contato"><span className="overline">VAMOS CONVERSAR</span><a className="contact-main" href={wa()} target="_blank" rel="noreferrer"><span>Seu próximo<br/>endereço.</span><ArrowUpRight/></a><div className="contact-bottom"><p>Conheça as unidades do Saphira Residence<br/>com a equipe comercial da Lumon.</p><a href={wa()} target="_blank" rel="noreferrer">Conversar pelo WhatsApp <ArrowUpRight size={19}/></a></div></section>
 </main>
 <footer><a href="#inicio" aria-label="Lumon, voltar ao início"><Logo/></a><div><span>ESCRITÓRIO LUMON</span><p>Rua Sergipe · São Cristóvão<br/>Lages · SC</p></div><div><a href="tel:+554932234426">(49) 3223-4426</a><p>Seg. a sex. · 08h às 18h</p><a href="https://www.instagram.com/lumon_construtora/" target="_blank" rel="noreferrer">Instagram ↗</a></div><small>© {new Date().getFullYear()} Lumon Construtora e Incorporadora. Perspectivas ilustrativas. Áreas, configurações e disponibilidade sujeitos à confirmação. Consulte o memorial descritivo.</small></footer>
 <Dialog open={menu} onOpenChange={setMenu}><DialogContent className="menu-dialog" showCloseButton={false}><DialogTitle className="sr-only">Menu Lumon</DialogTitle><DialogDescription className="sr-only">Navegação pelos empreendimentos</DialogDescription><button className="close-dialog" onClick={()=>setMenu(false)} aria-label="Fechar menu"><X/></button><Logo/>{[['Saphira Residence','saphira'],['Os ambientes','ambientes'],['Explore a planta','planta'],['Localização','localizacao'],['A Lumon','lumon'],['Monticello','monticello']].map(([label,id])=><a href={'#'+id} key={id} onClick={()=>setMenu(false)}>{label}<ArrowUpRight/></a>)}</DialogContent></Dialog>
 <Dialog open={film} onOpenChange={setFilm}><DialogContent className="film-dialog" showCloseButton={false}><DialogTitle className="sr-only">Filme Saphira Residence</DialogTitle><DialogDescription className="sr-only">Perspectiva ilustrativa da fachada do Saphira</DialogDescription><button className="close-dialog" onClick={()=>setFilm(false)} aria-label="Fechar filme"><X/></button>{film&&<video src="/images/saphira-filme.mp4" controls autoPlay playsInline/>}</DialogContent></Dialog>
 <Dialog open={gallery!==null} onOpenChange={v=>{if(!v)setGallery(null)}}><DialogContent className="gallery-dialog" showCloseButton={false}><DialogTitle>{media[gallery??0].name}</DialogTitle><DialogDescription className="sr-only">Perspectiva ilustrativa do Saphira Residence</DialogDescription><button className="close-dialog" onClick={()=>setGallery(null)} aria-label="Fechar galeria"><X/></button><Photo file={media[gallery??0].file} alt={media[gallery??0].name}/><div className="gallery-controls"><button onClick={()=>setGallery(v=>(Number(v)+3)%4)} aria-label="Imagem anterior"><ChevronLeft/></button><span>{(gallery??0)+1} / 4</span><button onClick={()=>setGallery(v=>(Number(v)+1)%4)} aria-label="Próxima imagem"><ChevronRight/></button></div></DialogContent></Dialog>
 <Dialog open={planOpen} onOpenChange={setPlanOpen}><DialogContent className="plan-dialog" showCloseButton={false}><DialogTitle>Planta original apresentada</DialogTitle><DialogDescription>Consulte medidas e disponibilidade com a equipe comercial.</DialogDescription><button className="close-dialog" onClick={()=>setPlanOpen(false)} aria-label="Fechar planta"><X/></button><Photo file="saphira-planta" alt="Planta apresentada pela Lumon com suíte, dormitório, estar, cozinha e varanda"/></DialogContent></Dialog>
 </div>
}
