"use client";
import {useEffect,useRef,useState} from 'react';
import {RotateCcw,Plus,Minus,Move,Maximize2} from 'lucide-react';
const zones=[['social','Estar e jantar','Ambientes integrados, com circulação entre estar, jantar e cozinha.'],['kitchen','Cozinha','A cozinha ocupa a faixa superior da planta apresentada.'],['bed','Dormitório flexível','Um segundo dormitório que pode acompanhar diferentes rotinas.'],['suite','Suíte','Área íntima localizada na porção inferior da planta.'],['balcony','Varanda','Extensão do estar na lateral da planta apresentada.']];
export default function PlanExplorer(){
 const host=useRef<HTMLDivElement>(null),api=useRef<any>(null);const [selected,setSelected]=useState('social'),[error,setError]=useState(false),[ready,setReady]=useState(false);
 useEffect(()=>{let disposed=false,cleanup=()=>{};
 Promise.all([import('three'),import('three/addons/controls/OrbitControls.js'),import('three/addons/renderers/SVGRenderer.js')]).then(([T,{OrbitControls},{SVGRenderer}])=>{
 if(disposed||!host.current)return;const container=host.current;let renderer:any;
 try{renderer=new T.WebGLRenderer({antialias:true,alpha:true})}catch{renderer=new SVGRenderer();renderer.setQuality('high')}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setClearColor(0x101418,0);container.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Modelo esquemático tridimensional da planta. Arraste para girar.');
 const scene=new T.Scene();const camera=new T.PerspectiveCamera(38,1,.1,100);camera.position.set(10,12,14);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,.3);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=8;controls.maxDistance=24;controls.maxPolarAngle=Math.PI*.46;controls.minPolarAngle=.15;controls.enableZoom=false;
 scene.add(new T.AmbientLight(0xffffff,1.1));scene.add(new T.HemisphereLight(0xffffff,0x7598b4,.8));const light=new T.DirectionalLight(0xffffff,1.6);light.position.set(-3,12,8);scene.add(light);
 const group=new T.Group();scene.add(group);const meshes:any[]=[];
 const box=(x:number,y:number,z:number,w:number,h:number,d:number,color:number)=>{const mesh=new T.Mesh(new T.BoxGeometry(w,h,d),new T.MeshStandardMaterial({color,roughness:.78,metalness:.05}));mesh.position.set(x,y,z);group.add(mesh);return mesh};
 const floor=(id:string,x:number,z:number,w:number,d:number)=>{let m=box(x,0,z,w,.15,d,0x858b8e);m.userData.zone=id;meshes.push(m)};
 // Schematic adjacency follows the supplied plan, without asserted dimensions.
 floor('kitchen',-.45,-3,5.8,1.8);floor('social',-1.9,-.15,2.9,3.8);floor('bed',1.05,-.9,2.8,2.4);floor('suite',1.3,3,3.9,2.8);floor('balcony',-2.15,2.5,2.4,1.65);floor('hall',.1,1.1,5.8,1.15);
 const wall=(x:number,z:number,w:number,d:number)=>box(x,.58,z,w,1.16,d,0xe6e6e2);
 wall(-3.4,-.45,.13,7);wall(-.5,-3.95,5.9,.13);wall(2.5,-2.3,.13,3.3);wall(3.3,2.85,.13,3.2);wall(1.25,4.45,4.2,.13);wall(-.8,3.6,.13,1.7);wall(.05,-.9,.13,2.5);wall(1.2,-2.13,2.5,.13);wall(2.65,1.2,1.3,.13);wall(.6,1.52,1.2,.13);wall(-2.55,1.6,1.5,.1);wall(-2.2,3.35,2.4,.1);
 // Simple volumes indicate circulation and use, not specifications or furnishings supplied.
 box(1.22,.23,3,1.5,.38,2,0xf7f4ee);box(1.22,.45,2.5,1.5,.13,.55,0xb3c0cc);box(1.25,.23,-.6,1.5,.38,1.85,0xf7f4ee);box(1.25,.45,-1.1,1.5,.13,.45,0xb3c0cc);
 box(-2.8,.28,.7,.65,.5,1.75,0xc2b5a5);box(-1.6,.27,.7,.7,.12,1,0x667681);box(-1.95,.4,-1.15,1.1,.13,1.25,0xb1a490);box(-.5,.4,-3.45,5,.8,.62,0xc5c9c7);
 const ring=new T.GridHelper(20,20,0x384149,0x20272c);ring.position.y=-.12;(ring.material as any).opacity=.12;(ring.material as any).transparent=true;scene.add(ring);
 const select=(id:string)=>{meshes.forEach(m=>m.material.color.setHex(m.userData.zone===id?0x367ba8:0x7d878d));setSelected(id)};select('social');
 let down={x:0,y:0};const ray=new T.Raycaster();const pointer=new T.Vector2();const pointerdown=(e:PointerEvent)=>{down={x:e.clientX,y:e.clientY}};const pointerup=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)return;const b=renderer.domElement.getBoundingClientRect();pointer.set(((e.clientX-b.left)/b.width)*2-1,-((e.clientY-b.top)/b.height)*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(meshes);if(hits[0]&&zones.some(z=>z[0]===hits[0].object.userData.zone))select(hits[0].object.userData.zone)};
 renderer.domElement.addEventListener('pointerdown',pointerdown);renderer.domElement.addEventListener('pointerup',pointerup);
 const resize=()=>{const w=container.clientWidth,h=container.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()};const ro=new ResizeObserver(resize);ro.observe(container);resize();let visible=false;const io=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting});io.observe(container);let frame=0;const loop=()=>{frame=requestAnimationFrame(loop);if(visible){controls.update();renderer.render(scene,camera)}};loop();setReady(true);setError(false);
 api.current={select,reset:()=>{camera.position.set(10,12,14);controls.target.set(0,0,.3)},zoom:(v:number)=>{const offset=camera.position.clone().sub(controls.target);const d=Math.max(8,Math.min(24,offset.length()*v));camera.position.copy(controls.target).add(offset.normalize().multiplyScalar(d))},top:()=>{camera.position.set(.01,18,.4);controls.target.set(0,0,.3)}};
 cleanup=()=>{cancelAnimationFrame(frame);io.disconnect();ro.disconnect();controls.dispose();renderer.dispose?.();scene.traverse((o:any)=>{o.geometry?.dispose();if(o.material) o.material.dispose?.()});renderer.domElement.remove();api.current=null};
 }).catch(()=>setError(true));return()=>{disposed=true;cleanup()};},[]);
 return <div className="plan-explorer"><div className="plan-canvas" ref={host}>{!ready&&!error&&<span className="model-loading">Preparando a planta…</span>}{error&&<div className="model-fallback"><img src="/images/saphira-planta.jpg" alt="Planta original do Saphira"/><p>A visualização 3D não está disponível neste dispositivo. Consulte a planta original.</p></div>}<span className="canvas-hint"><Move size={16}/> Arraste para girar · toque nos ambientes</span><div className="model-controls"><button aria-label="Aproximar planta" onClick={()=>api.current?.zoom(.85)}><Plus/></button><button aria-label="Afastar planta" onClick={()=>api.current?.zoom(1.15)}><Minus/></button><button aria-label="Vista superior" onClick={()=>api.current?.top()}><Maximize2/></button><button aria-label="Restaurar vista" onClick={()=>api.current?.reset()}><RotateCcw/></button></div></div><div className="plan-sidebar"><span className="overline">EXPLORE OS AMBIENTES</span><div className="room-buttons">{zones.map(z=><button key={z[0]} aria-pressed={selected===z[0]} onClick={()=>api.current?.select(z[0])}>{z[1]}<span>↗</span></button>)}</div><p>{zones.find(z=>z[0]===selected)?.[2]}</p><small>Estudo volumétrico ilustrativo, sem escala, baseado na imagem da planta. Não substitui o projeto arquitetônico nem o memorial descritivo.</small></div></div>
}
